name: Hello world
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: dubs11kt/sample-action@v1
        with:
          who-to-greet: 'dubs11kt'
