name: Hello world
on: [pull_request]
jobs:
  hello_world_job:
    if: ${{ startsWith(github.head_ref, 'thisis-') }}
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: test
        run: echo ${{ github.head_ref }}
